#include "ba11_n.h"
#include "imagedata/openrasterfile/openrasterfile.h"

//
// Support for the BA11-N Mounting Box
//
#include <functional>
#include <map>

using std::bind;
using std::placeholders::_1;
using std::map;
using std::get;
using std::make_unique;

// Constructor
// Create a window showing the BA11-N and devices and then start a thread
// handling the events and render the lamps and switches.
BA11_N::BA11_N (Bus* bus, Window *window, const BA11_NConfig& ba11_nConfig)
    :
    bus_ {bus},
    frontWindow_ {window},
    logo_ {ba11_nConfig.logo}
{
    createBezel (ba11_nConfig.cabinetPosition.value ());
}

// Destructor
BA11_N::~BA11_N ()
{}

// 
void BA11_N::createBezel (Cabinet::Position cabinetPosition)
{
    // Create the BA11-N panel at the specified position, width and height
    // and then start a loop handling the events and rendering lamps and
    // switches.
    // 
    // The operator switch panel contains three switches: AUX ON/OFF, HALT,
    // and RESTART. The functions and positions of the switches are as follows:
    // 
    // AUX ON/OFF OFF   As configured at the factory, this switch, when turned
    //                  off, removes ac power to the system. 
    //            ON    As configured at the factory, it turns on ac power. If
    //                  the automatic bootstrap is selected and the HALT switch
    //                  is up, the system boots.
    // 
    // HALT       Up    (Enable) This enables the processor to run
    //            Down  (HALT) This halts the processor, which responds to
    //                  console OOT commands.
    // 
    // RESTART          (Momentary switch) When this switch is activated,
    //                  the processor carries out a power-up sequence.
    //                  The HALT switch must be up (enable).
    // 
    // The switch panel also contains two indicators that provide the following
    // information:
    // 
    // PWR Success     On    This LED lights when the proper dc output voltages are
    //                  being generated by the H786 power supply.
    // 
    // RUN        On    This LED lights when the processor is in the run state.
    //                  It goes out when the processor is not executing
    //                  instructions.
    // 
    // Source: LSI-11 Systems Service Manual
    // 
    // At least for Windows, event handling has to be performed in the same
    // thread as in which the window has been created.
    //
    unique_ptr<ImageContainer> imageContainer =
        make_unique<OpenRasterFile> ("resources/BA11-N.ora");

    unique_ptr<PanelBuilder> panelBuilder =
        frontWindow_->createDataPanelBuilder (*imageContainer,
            cabinetPosition, BA11_NConfig::unitHeight);

    panelBuilder->createFront("BA11-N front", ba11_nFrontFrame);
    createLabel (panelBuilder, logo_);

    pwrOkLed_ = panelBuilder->createIndicator ("led PWR OFF",
        "led PWR ON", Indicator::State::Off);

    runLed_ = panelBuilder->createIndicator ("led RUN OFF", 
        "led RUN ON", Indicator::State::Off);

    restartSwitch_ = panelBuilder->createMultiPositionSwitch (
        {"switch RESTART OFF", "switch RESTART ON"},
        Button::MomentaryUpTwoPositionsState::Down,
        bind (&BA11_N::restartSwitchClicked, this, _1));

    haltSwitch_ = panelBuilder->createMultiPositionSwitch ({"switch HALT ON",
        "switch HALT OFF"},
        Button::TwoPositionsState::Up, bind (&BA11_N::haltSwitchToggled, this, _1));

    auxOnOffSwitch_ = panelBuilder->createMultiPositionSwitch ({"switch AUX OFF",
        "switch AUX ON"},
        Button::TwoPositionsState::Down, bind (&BA11_N::auxOnOffSwitchToggled, this, _1));

    frontWindow_->addPanel (panelBuilder->getPanel ());

    // Now the RUN led is created when can subscribe to the signal indicating
    // the state to be shown.
    bus_->SRUN().subscribe (bind (&BA11_N::SRUNReceiver, this, _1));
}

void BA11_N::createLabel (unique_ptr<PanelBuilder>& panelBuilder,
    BA11_NConfig::Logo logo)
{
    switch (logo)
    {
        case BA11_NConfig::Logo::PDP_1103L:
            panelBuilder->createFront ("label PDP-11/03");
            break;

        case BA11_NConfig::Logo::PDP_1123:
            panelBuilder->createFront ("label PDP-11/23");
            break;

        case BA11_NConfig::Logo::PDP_1123_PLUS:
            panelBuilder->createFront ("label PDP-11/23+");
            break;
    }
}

void BA11_N::restartSwitchClicked (Button::State state)
{
    if (get<Button::MomentaryUpTwoPositionsState> (state) == 
            Button::MomentaryUpTwoPositionsState::Up)
        bus_->RESET ().cycle ();
}

void BA11_N::haltSwitchToggled (Button::State state)
{
    switch (get<Button::TwoPositionsState> (state))
    {
        case Button::TwoPositionsState::Down:
            bus_->BHALT().set (true);
            break;

        case Button::TwoPositionsState::Up:
            bus_->BHALT().set (false);
            break;
    }
}

void BA11_N::auxOnOffSwitchToggled (Button::State state)
{
    switch (get<Button::TwoPositionsState> (state))
    {
        case Button::TwoPositionsState::Down:
            pwrOkLed_->show (Indicator::State::Off);
            bus_->BPOK ().set (false);
            break;

        case Button::TwoPositionsState::Up:
            // Set Power Success
            pwrOkLed_->show (Indicator::State::On);
            bus_->BPOK ().set (true);
            break;
    }
}

// The RUN led reflects the state of the SRUN signal.
void BA11_N::SRUNReceiver (bool signalValue)
{
    runLed_->show (signalValue ? Indicator::State::On : Indicator::State::Off);
}