;
; The PDP-11/20 has a KA11 processor with a KY11-A operator console.
;
; KY11-A options:
; cabinet = cabinetnumber / position in cabinet.
; switch_register = <value>
;
; A cabinet specification is obligatory. The KY11-A console has a height of
; of six rack units.
;
; The switch_register key defines the initial switch positions of the
; switch register. This may be helpful to boot the system more easily.
; Values can be given in octal representation and must be in the range
; 0-177777. The position of switches 17 and 18 cannot be defined but these
; aren't used anyway.
;
[KA11]

[KA11.KY11-A]
cabinet = 0/7
switch_register = 0173100

;
; MM11-E(X) - 4096/8192 word core memory module
;
; MM11-E(X) options:
; starting_address = <value>
; memory_extension = true | false
;
; The starting address must be on a 4KW boundary. The default value is 000000. 
; If the memory_extension option is set to true, the module is a MM1-EX which
; entails 8192 KW.
;
[MM11-E]
starting_address = 000000

[MM11-E]
starting_address = 020000

;
; M792 - Read only memory and MR11-DB bootstrap loader
;
; Several variants of the M792 exist, indicated as M792-Yx, where x
; states the installed option. The only option currently implemented
; is the M792-YB which provides a boot ROM for the TC11 DECtape and
; RC11, RF11, RK11, and RP11 disks. This option must be provided as
; the option for the M792.
; 
[M792]
option = M792-YB

;
; KW11-L Line Time Clock
;
; The KW11-L has no options
;
[KW11-L]

;
; DL11 - Asynchronous Line Interface
;
; DL11 options:
; address = <address>
; vector = <address>
;
; The DL11 base address must be in the range 0174000-0177770 and must be positioned
; on an 8 byte boundary (the lower three adress bits must equal zer0). The vector
; address must be in the range 0000-0376. The default base and vector addresses
; are 0177560 and 060, i.e. the stand addresses for use as console terminal.
;
[DL11]
; address = 0177560
; vector = 060

; RK11-D controller
;
; Controller options:
; address = <base address>
; vector = <address>
; units = 1-8
;
; A RK11-D can have one to eight RK05 devices attached to it. These are
; specified in RK11-D subsections.
;
[RK11-D]
units = 2

; RK05 drive options:
; spin-up-time = <#seconds>
; cabinet = cabinetnumber / position in cabinet
; filename = <filename>
; newfile = false | true
; write-protect = false | true
; overwrite = false | true (if true overwites existing file)
;
; A cabinet specification is obligatory; see the desciption above in the BA-11N
; section. A RK05 drive has a height of six rack units.
;
; The filename has to be specified on one of the following formats:
; - As an unqualified file path,
; - As a system-qualified file path in the format "Windows:<filename1>" and/or "Linux:<filename2>",
;   In this case filename 1 is used when running in a Windows system and filename2 is used for
;   Linux systems
; - As a combination of both, e.g. "Windows:<filename1> <filename2>". In this case filename1 is used
;   for Windows systems and filename2 for all other systems.
;
; A filename can be surrounded with curly braces to escape special characters in the file name
; such as the double colon.
;
;
[RK11-D.RK05]
unit = 0
cabinet = 0/13
;filename = \
;	Windows:{G:\projects\PDP-11\systems\XXDP\RK05\xxdp-rkdp.rk}, \
;	Linux:{/mnt/g/projects/PDP-11/systems/XXDP/RK05/xxdp-rkdp.rk}
filename = \
	Windows:{G:\src\sim-11\out\build\win-x64-debug\systems\xxdp-rkdp_gaf.rk}, \
	Linux:{/mnt/g/src/sim-11/out/build/win-x64-debug/systems/xxdp-rkdp_gaf.rk}
write-protect = true
spin-up-time = 10

[RK11-D.RK05]
unit=1
cabinet = 0/19
filename = scratch.rk05
newfile = true
overwrite = true
spin-up-time = 10

