#ifndef _DATA_FORMAT_H_
#define _DATA_FORMAT_H

// PDP-11 floating point data format
// See Digital Microcomputer Processors 1978-1979 pg. 11-6.

#define PDP11_F_EXPONENT_MASK  0x7F800000
#define PDP11_F_EXPONENT_SIZE  8
#define PDP11_F_EXPONENT_BIAS  ( 1 << ( PDP11_F_EXPONENT_SIZE - 1 ) )
#define PDP11_F_MANTISSA_MASK  0x007FFFFF
#define PDP11_F_MANTISSA_SIZE  23
#define PDP11_F_HIDDEN_BIT     ( 1 << PDP11_F_MANTISSA_SIZE )

#define IEEE_S_EXPONENT_MASK 0x7F800000
#define IEEE_S_EXPONENT_SIZE 8
#define IEEE_S_EXPONENT_BIAS ( ( 1 << ( IEEE_S_EXPONENT_SIZE - 1 ) ) - 1 )
#define IEEE_S_MANTISSA_MASK 0x007FFFFF
#define IEEE_S_MANTISSA_SIZE 23

#define MANTISSA_MASK PDP11_F_MANTISSA_MASK
#define MANTISSA_SIZE PDP11_F_MANTISSA_SIZE
#define HIDDEN_BIT    PDP11_F_HIDDEN_BIT

#define EXPONENT_ADJUSTMENT ( 1 + PDP11_F_EXPONENT_BIAS - IEEE_S_EXPONENT_BIAS )

#define IN_PLACE_EXPONENT_ADJUSTMENT \
           ( EXPONENT_ADJUSTMENT << IEEE_S_MANTISSA_SIZE )

// Floating point data format invariants
#define SIGN_BIT             0x80000000

#endif // _DATA_FORMAT_H